更新機能の追加
s1f102202998/django-test-exercise pull request #7
Opened 2023-07-13 08:51 UTC by s1f10220306

更新機能を追加しました。

2023-07-13 12:43 UTC, s1f102202998 requested changes
コンフリクトが起きているので、０１－８（３）を参考に修正お願いします。
１．ローカルリポジトリのmainブランチを最新化
(venv)
git checkout main
git pull origin main
２．作業ブランチに切り替えて、mainをマージ
git checkout feature/#5-add
git merge main
code .
３．コンフリクトしている箇所を修正
４．修正ができたらコミット、プッシュ
git add .
git commit -m " "
git push origin feature/#5-add

2023-07-14 02:12 UTC, s1f10220306 commented
コンフリクトを解消しました。
マージをお願いします。

2023-07-14 05:04 UTC, s1f102202998 commented on todo/views.py
> +  def update(request, task_id):
"def"の前にスペース空いてない？

2023-07-17 06:29 UTC, s1f10220306 commented on todo/views.py
> +  def update(request, task_id):
空いてた！修正しました。

2023-07-17 06:36 UTC, s1f102202998 requested changes

2023-07-17 06:36 UTC, s1f102202998 commented on todo/views.py
> +        tsak = Task.objects.get(pk=task_id)
"task"が"tsak"になっているから修正お願いします。
何度もごめん

2023-07-17 06:45 UTC, s1f10220306 commented on todo/views.py
> +        tsak = Task.objects.get(pk=task_id)
何回も間違ってごめん。確認お願いします。

2023-07-17 06:48 UTC, s1f102202998 approved these changes
OKです！

2023-07-17 06:48 UTC, merged